const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Baaba Devs";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "*******";
const forgetPassword = "Forget Password";
const login = "Log in";
const logout = "Log out";
const signup = "Sign Up";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Name";
const createNewAcccount = "or, create a new account";
const loginWith = "Log in with";
const loggedin = "Loggedin Successfully";
const loggedout = "Logged out  Successfully";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAcount = "Already Have an Account?";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = " Account";

// home screen string
const searchanything = "Search anything",
    todayDeal = "Today's deal",
    oldPass = "Old password",
    newPass = "New password",
    flashsale = "Flash Sale",
    topSellers = "Top Sellers",
    topCatregories = "Top Catregories",
    brand = "Top Categories",
    featuredCatregories = "Feature Cateroies",
    girlswatches = "Girls watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "Tshirts",
    girlsDress = "Girls Dresses",
    womenDress = "Women Dress",
    featuredProduct = " Featured Product";
const video = "Video",
    reviews = "Reviews",
    sellerpolicy = "Seller Policy",
    supportPolicy = "Support policy",
    productsyoumayLike = "Product may you like also",
    returnPolicy = "Return policy";
const womenClothing = "Women Clothing",
    menClothingFashoin = "Man Clothing & Fashion",
    compAccess = "Computer & Accessories",
    automobile = "Automobile",
    kidtoys = "Kids & Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    cellPhone = "Sellphone & Tab",
    furniture = "Furniture";
//profile string
const wishlist = "My Wishlist", order = " My Ordes", message = "Messages";
const paypal = "Paypal", stripe = "Stripe", cod = "Cash on delivary";
